version: "3"

services:
  some-mongo:
    image: mongo
  generator:
    build: .
    image: generator:dev
    ports:
      - "8899:8899"
    command: ["Rscript", "--vanilla", "plumber.R"]
  tester:
    build: ./tester
    image: tester:dev
    command: ["Rscript", "--vanilla", "main.R"]
  # validator:
  #   build: ./validator
  #   image: validator:dev
